# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [102]:
import numpy as np
arr=np.arange(0,10).reshape(2,5)
print(arr)
print(arr.ndim)
print("number of rows {} ".format(arr.shape[0]))

[[0 1 2 3 4]
 [5 6 7 8 9]]
2
number of rows 2 


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [103]:
arr1=np.arange(0,10).reshape(2,5)
print(arr1)
arr2=np.ones(10,dtype=np.int16).reshape(2,5)
print(arr2)
arr3=np.vstack((arr1,arr2))
print("After Stacking two Arrays"arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [14]:
arr4=np.hstack((arr1,arr2))
print(arr4)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [18]:
print("array of arrays \n{}".format(arr1))
one_dim_array=arr1.flatten()
print("\n one dimension array is  \n{}".format(one_dim_array))

array of arrays 
[[0 1 2 3 4]
 [5 6 7 8 9]]

 one dimension array is  
[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [27]:
ndim_array=np.arange(0,15).reshape(1,3,5)
print("N dim array \n{}".format(ndim_array))
one_dim_array=ndim_array.flatten()
print("one dim array \n{}".format(one_dim_array))

N dim array 
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
one dim array 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [30]:
print("one dimension array  = {}".format(one_dim_array))
high_dim_array=one_dim_array.reshape(5,3)
print("higher dimension array \n{}".format(high_dim_array))

one dimension array  = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
higher dimension array 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [33]:
sample_array=np.arange(0,25).reshape(5,5)
print("sample array is \n{}".format(sample_array))
sqr_array=np.square(sample_array)
print("square of 5x5 array is \n{}".format(sqr_array))

sample array is 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
square of 5x5 array is 
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [36]:
sample_Array=np.arange(0,30).reshape(5,6)
print("5x6 array before mean is  \n{}".format(sample_Array))
mean_array=sample_Array.mean()
print("mean of 5x6 array is \n{}".format(mean_array))

5x6 array before mean is  
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
mean of 5x6 array is 
14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [37]:
std_dev_array=sample_Array.std()
print("standard deviation of 5x6 array is \n{}".format(std_dev_array))

standard deviation of 5x6 array is 
8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [38]:
median_array=np.median(sample_Array)
print("median of 5x6 array is \n{}".format(median_array))

median of 5x6 array is 
14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [40]:
transpose_array=sample_Array.T
print("Transpose of 5x6 array will be 6x5 \n{}".format(transpose_array))

Transpose of 5x6 array will be 6x5 
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [74]:
sample4_array=np.random.randn(4,4)*100
print("4x4 sample array \n{}".format(sample4_array))
diagonal_Elements=sample4_array.diagonal()
print("Diagonal Elements of 4x4 array = {}".format(diagonal_Elements))
sum_diagonal_Elements=np.sum(diagonal_Elements)
print("Sum of diagonal element of 4x4 array = {}".format(sum_diagonal_Elements))

4x4 sample array 
[[-163.64678281  -58.35265803    2.35219861   16.36448411]
 [ -29.30011879  -63.64957751 -102.03894792 -168.95204935]
 [ -94.55391541  -85.63793357   -8.50704331 -178.80692701]
 [  28.53748079  -33.39072115   69.7171807   -20.95395694]]
Diagonal Elements of 4x4 array = [-163.64678281  -63.64957751   -8.50704331  -20.95395694]
Sum of diagonal element of 4x4 array = -256.7573605639424


## Question:13

### Find the determinant of the previous array in Q12?

In [75]:
print(sample4_array)
det_array=np.linalg.det(sample4_array)
print("Determinant of 4x4 array = {}".format(det_array))

[[-163.64678281  -58.35265803    2.35219861   16.36448411]
 [ -29.30011879  -63.64957751 -102.03894792 -168.95204935]
 [ -94.55391541  -85.63793357   -8.50704331 -178.80692701]
 [  28.53748079  -33.39072115   69.7171807   -20.95395694]]
Determinant of 4x4 array = 123755512.22736405


## Question:14

### Find the 5th and 95th percentile of an array?

In [80]:
   
print("5th percentile of 4x4 array after flattening =  {}  ".format(np.percentile(sample4_array, 5)))
print("95th  percentile of 4x4 array after flattening = {} ".format(np.percentile(sample4_array, 95)))

5th percentile of 4x4 array after flattening =  -171.4157687651107  
95th  percentile of 4x4 array after flattening = 38.83240576984028 


## Question:15

### How to find if a given array has any null values?

In [101]:
sample_array=np.array([1,3,4,5,6,np.nan])
res=np.isnan(sample_array).any()

print(res)

True
