# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_array=np.empty(10)
null_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
new_vector=np.arange(10,50)
new_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
print(new_vector.shape)

(40,)


5. Print the type of the previous array in question 3

In [5]:
print(type(new_vector))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [7]:
print(new_vector.ndim)

1


8. Create a boolean array with all the True values

In [8]:
boolean_array=np.full(10,True,dtype=np.bool)
print(boolean_array)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [9]:
n2d_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n2d_array)
print(n2d_array.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


10. Create a three dimensional array



In [10]:
n3d_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(n3d_array)
print(n3d_array.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
vectorSample=np.array(range(10))
print(type(vectorSample))
print("Orginal vector ",vectorSample)
rev_vec=np.flip(vectorSample,axis=0)
print("Reverse Vector ",rev_vec)

<class 'numpy.ndarray'>
Orginal vector  [0 1 2 3 4 5 6 7 8 9]
Reverse Vector  [9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
array2=np.zeros(10)
array2[4]=1
print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr=np.array([1,2,3,4,5])
arrFloat=arr.astype(np.float64)
print(arrFloat)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1=np.array([[1.,2.,3.],[4.,5,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arrMult=arr1*arr2
print(arrMult)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arrrs=arr1==arr2
print(arrrs)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
odd_arr=arr[arr%2==1]
print(odd_arr)

[1 3 5]


18. Replace all odd numbers to -1 from previous array

In [18]:
arr[arr%2==1]=-1
print(arr)

[-1  2 -1  4 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr=np.arange(10)
arr[5:8]=12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
ones_arr=np.ones((6,6))
ones_arr[1:-1,1:-1]=0
print(ones_arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[arr2d==5]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,:]=64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr=np.arange(0,10).reshape(2,5)
print(arr[0:1,:])

[[0 1 2 3 4]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr=np.arange(0,10).reshape(2,5)
print(arr)
print(arr[1:2,1:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[6]]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr=np.arange(0,10).reshape(2,5)
print(arr)
print(arr[0:2,2:3])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
random_arr=np.random.random((10,10))
print(random_arr)
max = np.amax(random_arr)
print('Maximum value : ', max)
min = np.amin(random_arr)
print('Minimum value : ', min)

[[0.96584068 0.43938353 0.67004706 0.23486603 0.97132986 0.84916458
  0.69841489 0.96718619 0.95016555 0.82688493]
 [0.22930176 0.02741444 0.5238328  0.3525055  0.75418325 0.32583422
  0.42950699 0.04434174 0.20239315 0.75377593]
 [0.8719768  0.06225832 0.37278793 0.69705778 0.85893221 0.05413854
  0.5818707  0.97898921 0.42484196 0.11853152]
 [0.15323426 0.0109039  0.62266649 0.12759525 0.41408918 0.01300166
  0.34873711 0.4600952  0.51780801 0.63394158]
 [0.68657943 0.86951763 0.51872064 0.38001357 0.48196726 0.25274039
  0.58615358 0.20343188 0.58834614 0.76338074]
 [0.70484205 0.11482616 0.33811839 0.37989591 0.20086941 0.96575732
  0.65578642 0.79732254 0.29676635 0.54662311]
 [0.31531717 0.35156394 0.0082819  0.81658565 0.65869246 0.5924998
  0.65398183 0.56100275 0.20116917 0.85126802]
 [0.31734052 0.28820824 0.91063396 0.60080586 0.19589432 0.01583456
  0.28207273 0.65612082 0.90392808 0.90959463]
 [0.94011199 0.4639049  0.23211337 0.85752326 0.96828261 0.38325685
  0.80725028 

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b) 
print("Common elements between a and b are", c) 

Common elements between a and b are [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.where(np.in1d(a, b))[0]
print("position of matching between a and b are ", c)

position of matching between a and b are  [1 3 5 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
print("Data where names not equal to will")
print(data[names!='Will'])

[[ 0.56678432  1.24019232 -1.21507111 -2.70050666]
 [-0.75630238 -0.66780832 -0.54810811  1.13377355]
 [ 0.33269747  0.26366266 -1.19732239  0.14879361]
 [-0.63961199 -0.01095533 -0.17597177  0.2243072 ]
 [ 0.51138887 -0.75245015  1.6734733   0.6180522 ]
 [-0.50546074  0.03167122 -0.90766982  0.31659783]
 [ 0.19556049 -0.6084144   0.78234495  0.08745885]]
Data where names not equal to will
[[ 0.56678432  1.24019232 -1.21507111 -2.70050666]
 [-0.75630238 -0.66780832 -0.54810811  1.13377355]
 [-0.63961199 -0.01095533 -0.17597177  0.2243072 ]
 [-0.50546074  0.03167122 -0.90766982  0.31659783]
 [ 0.19556049 -0.6084144   0.78234495  0.08745885]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
print("Data where names not equal to will and Joe")
(arr > 5) & (arr < 20)
print(data[(names!='Will') & (names!='Joe')])

[[ 0.12052828 -0.13406643 -0.54696338 -0.29418758]
 [-0.16642682  0.52511059 -0.26015909 -0.10842662]
 [ 0.64554211 -0.43769132 -0.25917973  0.15178606]
 [ 1.02622435  1.848983    1.70639617  0.44499592]
 [ 0.94348991  0.29185887  1.03081706  0.92040609]
 [ 1.67471268  1.76568393 -0.0335065   1.03305509]
 [-1.42115851 -0.62863282  1.95590034  1.16917654]]
Data where names not equal to will and Joe
[[ 0.12052828 -0.13406643 -0.54696338 -0.29418758]
 [ 1.02622435  1.848983    1.70639617  0.44499592]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
d2Array=np.arange(1,16).reshape(5,3)
d2Array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
d3Array=np.arange(1,17).reshape(2,2,4)
d3Array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [33]:
transp=d3Array.transpose(2,1,0)
print(transp)

[[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr=np.arange(10)
sqrtarr=np.sqrt(arr)
sqrtarr[sqrtarr<0.5]=0
print(sqrtarr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
array1 = np.random.uniform(low=1, high=12, size=(10,)) 
array2 = np.random.uniform(low=1, high=12, size=(10,))
print(array1)
print(array2)
print("3rd array with maximum element between each : ")
array3=np.maximum(array1,array2)
print(array3)

[ 9.49119315  8.52527099  1.34127959  7.19559027 11.59777102  9.92472921
 10.74717572 10.00891092  9.20582286  6.45763183]
[ 4.93540695  1.36245014 10.43045498  9.95108564  9.19234511  2.58409348
  1.51774108  9.61144512  8.06683134 11.35503203]
3rd array with maximum element between each : 
[ 9.49119315  8.52527099 10.43045498  9.95108564 11.59777102  9.92472921
 10.74717572 10.00891092  9.20582286 11.35503203]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniqueArray=np.sort(np.unique(names))
print(uniqueArray)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
print("After removing the element from a that is present in b ",c)

After removing the element from a that is present in b  [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
print(newColumn)
resultantArray=np.delete(sampleArray,1,1)
print(resultantArray)
resultantArray1=np.append(resultantArray, newColumn.T, axis=1)
print(resultantArray1)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[10 10 10]]
[[34 73]
 [82 12]
 [53 66]]
[[34 73 10]
 [82 12 10]
 [53 66 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
print(x)
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(y)
z=np.dot(x,y)
print("resultant array ")
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
resultant array 
[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
array1 = np.random.uniform(low=1, high=100, size=(5,4))
print(array1)
arrayCUMSUM=array1.cumsum(axis=1)
print("cumulative sum of matrix : ")
print(arrayCUMSUM)

[[20.4208611  14.92588899  5.30931003 79.99470018]
 [93.76853483 38.77719607 41.12653622 27.55104724]
 [66.64905569 89.94827671 66.37058884 92.24048434]
 [64.72340165 60.87678624 11.75448768 53.77545466]
 [48.26460268 22.95780602 78.26771499 63.03923456]]
cumulative sum of matrix : 
[[ 20.4208611   35.34675009  40.65606012 120.6507603 ]
 [ 93.76853483 132.54573089 173.67226712 201.22331436]
 [ 66.64905569 156.59733241 222.96792125 315.20840558]
 [ 64.72340165 125.60018789 137.35467557 191.13013023]
 [ 48.26460268  71.2224087  149.49012369 212.52935825]]
